server:
  port: 8888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/api/customers/**
          - id: r2
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/products/**
